# Generated by Django 4.2.16 on 2024-12-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('spu_code', models.CharField(max_length=50, unique=True, verbose_name='SPU编码')),
                ('spu_name', models.CharField(max_length=200, verbose_name='SPU名称')),
                ('spu_remark', models.TextField(blank=True, null=True, verbose_name='SPU备注')),
                ('sales_channel', models.IntegerField(choices=[(1, '线上商城'), (2, '线下门店'), (3, '电商平台'), (4, '批发渠道'), (5, '其他渠道')], default=1, verbose_name='销售渠道')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spus', to='gallery.category', verbose_name='所属类目')),
            ],
            options={
                'verbose_name': 'SPU',
                'verbose_name_plural': 'SPU',
                'db_table': 'gallery_spu',
                'ordering': ['-id'],
            },
        ),
    ]
