# Generated by Django 4.2.16 on 2024-12-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_spu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='分类图片'),
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('sku_name', models.CharField(max_length=200, verbose_name='SKU名称')),
                ('provider_name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('weight', models.PositiveIntegerField(verbose_name='重量(g)')),
                ('plating_process', models.CharField(max_length=100, verbose_name='电镀工艺')),
                ('color', models.CharField(choices=[('gold', '金色'), ('silver', '银色'), ('rose_gold', '玫瑰金'), ('black', '黑色'), ('white', '白色'), ('blue', '蓝色'), ('red', '红色'), ('green', '绿色'), ('purple', '紫色'), ('yellow', '黄色'), ('other', '其他')], max_length=20, verbose_name='颜色')),
                ('length', models.PositiveIntegerField(verbose_name='长度(mm)')),
                ('width', models.PositiveIntegerField(verbose_name='宽度(mm)')),
                ('height', models.PositiveIntegerField(verbose_name='高度(mm)')),
                ('other_dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='其他尺寸')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='SKU图片')),
                ('material', models.CharField(max_length=100, verbose_name='材质')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='gallery.spu', verbose_name='所属SPU')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'db_table': 'gallery_sku',
                'ordering': ['-id'],
            },
        ),
    ]
